version: '3'

services:
  label-studio:
    image: heartexlabs/label-studio:latest
    container_name: labelstudio
    ports:
      - '8080:8080'
    environment:
      - DJANGO_DB=default
      - POSTGRE_NAME=labelstudio_db
      - POSTGRE_USER=labelstudio_user
      - POSTGRE_PASSWORD=somepassword
      - POSTGRE_PORT=5432
      - POSTGRE_HOST=db
    depends_on:
      - db
  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_DB=labelstudio_db
      - POSTGRES_USER=labelstudio_user
      - POSTGRES_PASSWORD=somepassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
